------------------怨꾩젙 �깮�꽦 諛� 沅뚰븳 遺��뿬 --------------------------
-------------------------------------------------------------
CREATE USER STUDDYPE IDENTIFIED BY STUDDYPE;
GRANT CONNECT, RESOURCE TO STUDDYPE;
------------------ DROP SEQUENCE ----------------------------
-------------------------------------------------------------
DROP SEQUENCE MEMBERSEQ;
DROP SEQUENCE SISEQ;
DROP SEQUENCE GUSEQ;
DROP SEQUENCE CATEGORYSEQ;

DROP SEQUENCE STUDYSEQ;

DROP SEQUENCE NOTICEBOARDSEQ;
DROP SEQUENCE NOTICEREPLYSEQ;
DROP SEQUENCE NOTICEFILESEQ;
DROP SEQUENCE NOTICEGROUPSEQ;

DROP SEQUENCE FREEBOARDSEQ;
DROP SEQUENCE FREEREPLYSEQ;
DROP SEQUENCE FREEGROUPSEQ;
DROP SEQUENCE FREEFILESEQ;

DROP SEQUENCE BOOKSEQ;
DROP SEQUENCE BOOKREPLYSEQ;
DROP SEQUENCE BOOKGROUPSEQ;

DROP SEQUENCE PHOTOBOARDSEQ;
DROP SEQUENCE PHOTOREPLYSEQ;
DROP SEQUENCE PHOTOFILESEQ;
DROP SEQUENCE PHOTOGROUPSEQ;

DROP SEQUENCE DATABOARDSEQ; 
DROP SEQUENCE DATAREPLYSEQ; 
DROP SEQUENCE DATAFILESEQ; 
DROP SEQUENCE DATAGROUPSEQ; 

DROP SEQUENCE MEETBOARDSEQ;
DROP SEQUENCE MEETREPLYSEQ;
DROP SEQUENCE MEETGROUPSEQ;
-------------------------------------------------------------
--SELECT * FROM ALL_TABLES WHERE OWNER = 'STUDDYPE'; --�쟾泥� �뀒�씠釉� �솗�씤
-------------------------------------------------------------
------------------ DROP TABLE -------------------------------
-------------------------------------------------------------
DROP TABLE MEMBER;
DROP TABLE LOCATION_SI;
DROP TABLE LOCATION_GU;

DROP TABLE STUDY_CATEGORY;
DROP TABLE STUDY;
DROP TABLE STUDY_MEMBER;
DROP TABLE STUDY_APPLYING;

DROP TABLE NOTICE_BOARD;
DROP TABLE NOTICE_REPLY;
DROP TABLE NOTICE_FILE;

DROP TABLE FREE_BOARD;
DROP TABLE FREE_REPLY;
DROP TABLE FREE_FILE;

DROP TABLE BOOK;
DROP TABLE BOOK_REPLY;

DROP TABLE PHOTO_BOARD;
DROP TABLE PHOTO_REPLY;
DROP TABLE PHOTO_FILE;

DROP TABLE DATA_BOARD;
DROP TABLE DATA_REPLY;
DROP TABLE DATA_FILE;

DROP TABLE MEET_BOARD;
DROP TABLE MEET_VOTE;
DROP TABLE MEET_REPLY;
------------------ SEQUENCE_NOCACHE -------------------------
-------------------------------------------------------------
CREATE SEQUENCE MEMBERSEQ NOCACHE;  --�쉶�썝 �떆���뒪
CREATE SEQUENCE SISEQ NOCACHE;  --吏��뿭(�떆) �떆���뒪
CREATE SEQUENCE GUSEQ NOCACHE;  --吏��뿭(援�) �떆���뒪
CREATE SEQUENCE CATEGORYSEQ NOCACHE;  --移댄뀒怨좊━ �떆���뒪

CREATE SEQUENCE STUDYSEQ NOCACHE;  --�뒪�꽣�뵒 �떆���뒪

CREATE SEQUENCE NOTICEBOARDSEQ NOCACHE;  --怨듭��궗�빆寃뚯떆湲�
CREATE SEQUENCE NOTICEREPLYSEQ NOCACHE;  --怨듭��궗�빆 �뙎湲�
CREATE SEQUENCE NOTICEFILESEQ NOCACHE;  --怨듭��궗�빆 寃뚯떆洹� �궗吏�
CREATE SEQUENCE NOTICEGROUPSEQ NOCACHE; -- 怨듭�寃뚯떆�뙋 �뙎湲� 洹몃９�닚�꽌 �떆���뒪

CREATE SEQUENCE FREEBOARDSEQ NOCACHE;  --�옄�쑀寃뚯떆�뙋寃뚯떆湲�
CREATE SEQUENCE FREEREPLYSEQ NOCACHE;  --�옄�쑀寃뚯떆�뙋 �뙎湲�
CREATE SEQUENCE FREEGROUPSEQ NOCACHE;  --�옄�쑀寃뚯떆�뙋 �뙎湲� 洹몃９
CREATE SEQUENCE FREEFILESEQ NOCACHE;  --�옄�쑀 寃뚯떆�뙋 寃뚯떆洹� �궗吏�

CREATE SEQUENCE BOOKSEQ NOCACHE; -- 遺곴쾶�떆�뙋
CREATE SEQUENCE BOOKREPLYSEQ NOCACHE;  -- �뙎湲�
CREATE SEQUENCE BOOKGROUPSEQ NOCACHE;  --�옄�쑀寃뚯떆�뙋 �뙎湲� 洹몃９

CREATE SEQUENCE PHOTOBOARDSEQ NOCACHE;  --�궗吏꾧쾶�떆�뙋寃뚯떆湲�
CREATE SEQUENCE PHOTOREPLYSEQ NOCACHE;  --�궗吏꾧쾶�떆�뙋 �뙎湲�
CREATE SEQUENCE PHOTOFILESEQ NOCACHE;  --�궗吏� 寃뚯떆�뙋 寃뚯떆洹� �궗吏�
CREATE SEQUENCE PHOTOGROUPSEQ NOCACHE; --�궗吏� �뙎湲� 洹몃９�닚�꽌

CREATE SEQUENCE DATABOARDSEQ NOCACHE;  --�옄猷뚯떎寃뚯떆�뙋寃뚯떆湲�
CREATE SEQUENCE DATAREPLYSEQ NOCACHE;  --�옄猷뚯떎寃뚯떆�뙋 �뙎湲�
CREATE SEQUENCE DATAFILESEQ NOCACHE;  --�옄猷뚯떎 寃뚯떆�뙋 寃뚯떆湲� �궗吏�
CREATE SEQUENCE DATAGROUPSEQ NOCACHE; -- �옄猷뚯떎 �뙎湲� 洹몃９�닚�꽌 �떆���뒪

CREATE SEQUENCE MEETBOARDSEQ NOCACHE;  --紐⑥엫寃뚯떆�뙋 寃뚯떆湲�
CREATE SEQUENCE MEETREPLYSEQ NOCACHE;  --紐⑥엫寃뚯떆�뙋 �뙎湲�
CREATE SEQUENCE MEETGROUPSEQ NOCACHE;  --紐⑥엫寃뚯떆�뙋 �뙎湲� 洹몃９
-------------------------------------------------------------

------------------ DROP CONSTRAINTS -------------------------
-------------------------------------------------------------
DROP TABLE LOCATION_SI CASCADE CONSTRAINTS;
DROP TABLE LOCATION_GU CASCADE CONSTRAINTS;
DROP TABLE STUDY_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE LOCATION_SI CASCADE CONSTRAINTS;
DROP TABLE STUDY CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE STUDY_APPLYING CASCADE CONSTRAINTS;
DROP TABLE NOTICE_BOARD CASCADE CONSTRAINTS;
DROP TABLE NOTICE_REPLY CASCADE CONSTRAINTS;
DROP TABLE MEET_REPLY CASCADE CONSTRAINTS;
DROP TABLE PHOTO_BOARD CASCADE CONSTRAINTS;
DROP TABLE PHOTO_FILE CASCADE CONSTRAINTS;
DROP TABLE PHOTO_REPLY CASCADE CONSTRAINTS;

-------------------------------------------------------------

------------------ CREATE TABLE -----------------------------
-------------------------------------------------------------

--�쉶�썝 �뀒�씠釉� 
CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY, --踰덊샇
    MEM_ID VARCHAR2(100) NOT NULL, --�븘�씠�뵒
    MEM_PW VARCHAR2(100) NOT NULL, --鍮꾨�踰덊샇
    MEM_NAME VARCHAR2(100) NOT NULL, --�씠由�
    MEM_RNO VARCHAR2(14) UNIQUE NOT NULL, --二쇰�쇰쾲�샇
    MEM_GENDER VARCHAR2(1) CHECK(MEM_GENDER IN('M','F')) NOT NULL ,--�꽦蹂� M,F
    MEM_PHONE VARCHAR2(13) NOT NULL, --�빖�뱶�룿 踰덊샇
    MEM_EMAIL VARCHAR2(100) NOT NULL -- �씠硫붿씪    
);

------吏��뿭 移댄뀒怨좊━ 
---�떆
CREATE TABLE LOCATION_SI(
    SI_NO NUMBER PRIMARY KEY, --�떆 踰덊샇
    SI_NAME VARCHAR2(50) NOT NULL UNIQUE --�떆 �씠由�
);

--援�
CREATE TABLE LOCATION_GU(
    GU_NO NUMBER PRIMARY KEY, --援� 踰덊샇
    SI_NO  NUMBER, -- �떆 踰덊샇 �쇅�옒�궎
    GU_NAME VARCHAR(50) NOT NULL, -- 援� �씠由�    
    FOREIGN KEY(SI_NO) REFERENCES LOCATION_SI(SI_NO)  ON DELETE CASCADE
);

--�뒪�꽣�뵒 移댄뀒怨좊━
CREATE TABLE STUDY_CATEGORY(
    CATE_NO NUMBER PRIMARY KEY, --移댄뀒怨좊━ 踰덊샇
    CATE_NAME VARCHAR2(100) NOT NULL UNIQUE --移댄뀒怨좊━ �씠由�
);

--�뒪�꽣�뵒 �뀒�씠釉�
 CREATE TABLE STUDY(
    S_NO NUMBER PRIMARY KEY, --�뒪�꽣�뵒 踰덊샇
    LEADER_NO NUMBER NOT NULL, --���옣 踰덊샇   [ �쇅�옒�궎 ]
    S_NAME VARCHAR2(100) NOT NULL, --�뒪�꽣�뵒 �씠由�
    S_INFO VARCHAR2(100) NOT NULL, --�뒪�꽣�뵒 �븳以� �냼媛�
    S_CONTENT LONG NOT NULL, --�뒪�꽣�뵒 �옄�꽭�븳 �냼媛�
    S_PHOTO VARCHAR2(4000) NOT NULL,
    CATE_NO NUMBER NOT NULL, --�뒪�꽣�뵒 移댄뀒怨좊━   [�쇅�옒�궎]
    SI_NO NUMBER NOT NULL, --�뒪�꽣�뵒 吏��뿭(�떆)    [�쇅�옒�궎]
    GU_NO NUMBER NOT NULL, --�뒪�꽣�뵒 吏��뿭(援�)   [�쇅�옒�궎]
    S_MAXCNT NUMBER NOT NULL, --�뒪�꽣�뵒 理쒕� �씤�썝
    S_CURRENTCNT NUMBER DEFAULT 1 NOT NULL, --�뒪�꽣�뵒 �쁽�옱 �씤�썝 
    FOREIGN KEY (LEADER_NO) REFERENCES MEMBER(MEM_NO) ON DELETE CASCADE,
    FOREIGN KEY (CATE_NO) REFERENCES STUDY_CATEGORY(CATE_NO) ON DELETE SET NULL,
    FOREIGN KEY (SI_NO) REFERENCES LOCATION_SI(SI_NO) ON DELETE SET NULL,
    FOREIGN KEY (GU_NO) REFERENCES LOCATION_GU(GU_NO) ON DELETE SET NULL
 );

-- �뒪�꽣�뵒 ���썝紐⑸줉
CREATE TABLE STUDY_MEMBER(
    S_NO NUMBER,
    MEM_NO NUMBER,
    FOREIGN KEY(S_NO) REFERENCES STUDY(S_NO) ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE,
    PRIMARY KEY(S_NO, MEM_NO)    
);

--�뒪�꽣�뵒 媛��엯�떊泥� �쁽�솴
CREATE TABLE STUDY_APPLYING(
    S_NO NUMBER,
    MEM_NO NUMBER,
    AGREE VARCHAR2(1) DEFAULT 'D' CHECK(AGREE IN('Y','N','D')) NOT NULL ,-- �닔�씫�쁽�솴 Y,N,D
    INFO VARCHAR2(1000) NOT NULL, --�옄湲곗냼媛�
    FOREIGN KEY(S_NO) REFERENCES STUDY(S_NO) ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE,
    PRIMARY KEY(S_NO, MEM_NO)        
);

-------------------------------------------------------------

------------------ CREATE BOARD -----------------------------
-------------------------------------------------------------

--怨듭��궗�빆 寃뚯떆�뙋
CREATE TABLE NOTICE_BOARD(
    B_NO NUMBER PRIMARY KEY, --寃뚯떆湲� 踰덊샇
    S_NO NUMBER NOT NULL,   --�뒪�꽣�뵒踰덊샇 [�쇅�옒�궎]
    B_TITLE VARCHAR2(1000) NOT NULL,--寃뚯떆湲� �젣紐�
    B_WRITER NUMBER NOT NULL, -- �옉�꽦�옄 (�쉶�썝踰덊샇) [�쇅�옒�궎]
    B_CONTENT LONG NOT NULL, --寃뚯떆湲� �궡�슜
    B_REGDATE DATE NOT NULL,--寃뚯떆湲� �옉�꽦 �떆媛�
    B_CNT NUMBER DEFAULT 0, -- 議고쉶�닔
    FOREIGN KEY(S_NO) REFERENCES STUDY(S_NO) ON DELETE CASCADE,
    FOREIGN KEY(B_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE    
);

--怨듭��궗�빆 寃뚯떆�뙋 �뙎湲�
CREATE TABLE NOTICE_REPLY(
    R_NO NUMBER PRIMARY KEY, -- �뙎湲� 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲� 踰덊샇
    R_GROUPNO NUMBER NOT NULL, -- �뙎湲� 洹몃９ 踰덊샇
    R_CLASS NUMBER NOT NULL, -- �뙎湲� 怨꾩링
    R_ORDER NUMBER NOT NULL,--�뙎湲�,�떟湲� �닚�꽌    
    R_WRITER NUMBER NOT NULL, -- �뙎湲� �옉�꽦�옄 (�쉶�썝踰덊샇)
    R_COMMENT VARCHAR2(1000) NOT NULL, --�뙎湲� �궡�슜
    R_REGDATE DATE NOT NULL,--�뙎湲� �옉�꽦 �떆媛�
    FOREIGN KEY(R_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE ,
    FOREIGN KEY(B_NO) REFERENCES NOTICE_BOARD(B_NO) ON DELETE CASCADE    
);

--怨듭��궗�빆 寃뚯떆�뙋 �궗吏�
CREATE TABLE NOTICE_FILE(
    F_NO NUMBER PRIMARY KEY, --�뙆�씪 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲�踰덊샇
    F_NAME VARCHAR2(1000) NOT NULL, --�뙆�씪 �떎�젣�씠由�
    F_SIZE NUMBER NOT NULL, --�뙆�씪 �겕湲� KB
    F_URL VARCHAR2(4000) NOT NULL, --�뙆�씪 媛��긽�씠由�
    FOREIGN KEY(B_NO) REFERENCES NOTICE_BOARD(B_NO) ON DELETE CASCADE    
);

--�옄�쑀 寃뚯떆�뙋
CREATE TABLE FREE_BOARD(
    B_NO NUMBER PRIMARY KEY, --寃뚯떆湲� 踰덊샇
    S_NO NUMBER NOT NULL,   --�뒪�꽣�뵒踰덊샇 [�쇅�옒�궎]
    B_TITLE VARCHAR2(1000) NOT NULL,--寃뚯떆湲� �젣紐�
    B_WRITER NUMBER NOT NULL, -- �옉�꽦�옄 (�쉶�썝踰덊샇) [�쇅�옒�궎]
    B_CONTENT LONG NOT NULL, --寃뚯떆湲� �궡�슜
    B_REGDATE DATE NOT NULL,--寃뚯떆湲� �옉�꽦 �떆媛�
     B_CNT NUMBER DEFAULT 0, -- 議고쉶�닔
      FOREIGN KEY(S_NO) REFERENCES STUDY(S_NO) ON DELETE CASCADE,
    FOREIGN KEY(B_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE    
);

--�옄�쑀 寃뚯떆�뙋 �뙎湲�
CREATE TABLE FREE_REPLY(
    R_NO NUMBER PRIMARY KEY, -- �뙎湲� 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲� 踰덊샇
    R_GROUPNO NUMBER NOT NULL, -- �뙎湲� 洹몃９ 踰덊샇
    R_CLASS NUMBER NOT NULL, -- �뙎湲� 怨꾩링
    R_ORDER NUMBER NOT NULL,--�뙎湲�,�떟湲� �닚�꽌    
    R_WRITER NUMBER NOT NULL, -- �뙎湲� �옉�꽦�옄 (�쉶�썝踰덊샇)
    R_COMMENT VARCHAR2(1000) NOT NULL, --�뙎湲� �궡�슜
    R_REGDATE DATE NOT NULL,--�뙎湲� �옉�꽦 �떆媛�
    FOREIGN KEY(R_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE ,
    FOREIGN KEY(B_NO) REFERENCES FREE_BOARD(B_NO) ON DELETE CASCADE    
);

--�옄�쑀 寃뚯떆�뙋 �궗吏�
CREATE TABLE FREE_FILE(
    F_NO NUMBER PRIMARY KEY, --�뙆�씪 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲�踰덊샇
    F_NAME VARCHAR2(1000) NOT NULL, --�뙆�씪 �떎�젣�씠由�
    F_SIZE NUMBER NOT NULL, --�뙆�씪 �겕湲� KB
    F_URL VARCHAR2(4000) NOT NULL, --�뙆�씪 媛��긽�씠由�
    FOREIGN KEY(B_NO) REFERENCES FREE_BOARD(B_NO) ON DELETE CASCADE    
);

-- �븰�뒿 �룄�꽌 寃뚯떆�뙋
CREATE TABLE BOOK(
    B_NO NUMBER PRIMARY KEY, --寃뚯떆湲� 踰덊샇
    S_NO NUMBER NOT NULL,   --�뒪�꽣�뵒踰덊샇 [�쇅�옒�궎]
    B_TITLE VARCHAR2(1000) NOT NULL,--寃뚯떆湲� �젣紐�
    B_WRITER NUMBER NOT NULL, -- �옉�꽦�옄 (�쉶�썝踰덊샇) [�쇅�옒�궎]
    B_CONTENT VARCHAR2(2000) NOT NULL, --寃뚯떆湲� �궡�슜
    B_REGDATE DATE NOT NULL,--寃뚯떆湲� �옉�꽦 �떆媛�
    BOOK_TITLE VARCHAR2(500) NOT NULL, --梨� �씠由�
    BOOK_AUTHOR VARCHAR2(500) NOT NULL, -- 梨� ���옄
    BOOK_PUBLISH VARCHAR2(500) NOT NULL, -- 梨� 異쒗뙋�궗
    BOOK_IMG VARCHAR2(1000) NOT NULL, --�룄�꽌 �씠誘몄� URL
    BOOK_URL VARCHAR2(1000) NOT NULL, -- �룄�꽌 URL
    BOOK_ISMAIN VARCHAR2(1) DEFAULT 'N' CHECK (BOOK_ISMAIN IN ('Y','N')) NOT NULL, -- ���몴�룄�꽌 Y,N
    FOREIGN KEY(S_NO) REFERENCES STUDY(S_NO) ON DELETE CASCADE,
    FOREIGN KEY(B_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE    
);

--�룄�꽌 寃뚯떆�뙋 �뙎湲�
CREATE TABLE BOOK_REPLY(
    R_NO NUMBER PRIMARY KEY, -- �뙎湲� 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲� 踰덊샇
    R_GROUPNO NUMBER NOT NULL, -- �뙎湲� 洹몃９ 踰덊샇
    R_CLASS NUMBER NOT NULL, -- �뙎湲� 怨꾩링
    R_ORDER NUMBER NOT NULL,--�뙎湲�,�떟湲� �닚�꽌    
    R_WRITER NUMBER NOT NULL, -- �뙎湲� �옉�꽦�옄 (�쉶�썝踰덊샇)
    R_COMMENT VARCHAR2(1000) NOT NULL, --�뙎湲� �궡�슜
    R_REGDATE DATE NOT NULL,--�뙎湲� �옉�꽦 �떆媛�
    FOREIGN KEY(R_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE ,
    FOREIGN KEY(B_NO) REFERENCES BOOK(B_NO) ON DELETE CASCADE    
);

--�궗吏� 寃뚯떆�뙋
CREATE TABLE PHOTO_BOARD(
    B_NO NUMBER PRIMARY KEY, --寃뚯떆湲� 踰덊샇
    S_NO NUMBER NOT NULL,   --�뒪�꽣�뵒踰덊샇 [�쇅�옒�궎]
    B_TITLE VARCHAR2(1000) NOT NULL,--寃뚯떆湲� �젣紐�
    B_WRITER NUMBER NOT NULL, -- �옉�꽦�옄 (�쉶�썝踰덊샇) [�쇅�옒�궎]
    B_CONTENT VARCHAR2(4000) NOT NULL, --寃뚯떆湲� �궡�슜
    B_REGDATE DATE NOT NULL,--寃뚯떆湲� �옉�꽦 �떆媛�
    B_CNT NUMBER DEFAULT 0, -- 議고쉶�닔
    FOREIGN KEY(S_NO) REFERENCES STUDY(S_NO) ON DELETE CASCADE,
    FOREIGN KEY(B_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE    
);

--�궗吏� 寃뚯떆�뙋 �뙎湲�
CREATE TABLE PHOTO_REPLY(
    R_NO NUMBER PRIMARY KEY, -- �뙎湲� 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲� 踰덊샇
    R_GROUPNO NUMBER NOT NULL, -- �뙎湲� 洹몃９ 踰덊샇
    R_CLASS NUMBER NOT NULL, -- �뙎湲� 怨꾩링
    R_ORDER NUMBER NOT NULL,--�뙎湲�,�떟湲� �닚�꽌    
    R_WRITER NUMBER NOT NULL, -- �뙎湲� �옉�꽦�옄 (�쉶�썝踰덊샇)
    R_COMMENT VARCHAR2(1000) NOT NULL, --�뙎湲� �궡�슜
    R_REGDATE DATE NOT NULL,--�뙎湲� �옉�꽦 �떆媛�
    FOREIGN KEY(R_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE ,
    FOREIGN KEY(B_NO) REFERENCES PHOTO_BOARD(B_NO) ON DELETE CASCADE    
);

--�궗吏� 寃뚯떆�뙋 �궗吏�
CREATE TABLE PHOTO_FILE(
    F_NO NUMBER PRIMARY KEY, --�뙆�씪 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲�踰덊샇
    F_NAME VARCHAR2(1000) NOT NULL, --�뙆�씪 �떎�젣�씠由�
    F_SIZE NUMBER NOT NULL, --�뙆�씪 �겕湲� KB
    F_URL VARCHAR2(4000) NOT NULL, --�뙆�씪 媛��긽�씠由�
    PHOTO_ISMAIN VARCHAR2(1) DEFAULT 'N' CHECK (PHOTO_ISMAIN IN ('Y','N')) NOT NULL, -- ���몴�궗吏� Y,N
    FOREIGN KEY(B_NO) REFERENCES PHOTO_BOARD(B_NO) ON DELETE CASCADE    
);

--�븰�뒿�옄猷뚯떎 寃뚯떆�뙋
CREATE TABLE DATA_BOARD(
    B_NO NUMBER PRIMARY KEY, --寃뚯떆湲� 踰덊샇
    S_NO NUMBER NOT NULL,   --�뒪�꽣�뵒踰덊샇 [�쇅�옒�궎]
    B_TITLE VARCHAR2(1000) NOT NULL,--寃뚯떆湲� �젣紐�
    B_WRITER NUMBER NOT NULL, -- �옉�꽦�옄 (�쉶�썝踰덊샇) [�쇅�옒�궎]
    B_CONTENT LONG NOT NULL, --寃뚯떆湲� �궡�슜
    B_REGDATE DATE NOT NULL,--寃뚯떆湲� �옉�꽦 �떆媛�
    B_CNT NUMBER DEFAULT 0, -- 議고쉶�닔
    FOREIGN KEY(S_NO) REFERENCES STUDY(S_NO) ON DELETE CASCADE,
    FOREIGN KEY(B_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE    
);

--�븰�뒿�옄猷뚯떎 寃뚯떆�뙋 �뙎湲�
CREATE TABLE DATA_REPLY(
    R_NO NUMBER PRIMARY KEY, -- �뙎湲� 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲� 踰덊샇
    R_GROUPNO NUMBER NOT NULL, -- �뙎湲� 洹몃９ 踰덊샇
    R_CLASS NUMBER NOT NULL, -- �뙎湲� 怨꾩링
    R_ORDER NUMBER NOT NULL,--�뙎湲�,�떟湲� �닚�꽌    
    R_WRITER NUMBER NOT NULL, -- �뙎湲� �옉�꽦�옄 (�쉶�썝踰덊샇)
    R_COMMENT VARCHAR2(1000) NOT NULL, --�뙎湲� �궡�슜
    R_REGDATE DATE NOT NULL,--�뙎湲� �옉�꽦 �떆媛�
    FOREIGN KEY(R_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE ,
    FOREIGN KEY(B_NO) REFERENCES DATA_BOARD(B_NO) ON DELETE CASCADE    
);


--�븰�뒿�옄猷뚯떎 寃뚯떆�뙋 �궗吏�
CREATE TABLE DATA_FILE(
    F_NO NUMBER PRIMARY KEY, --�뙆�씪 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲�踰덊샇
    F_NAME VARCHAR2(1000) NOT NULL, --�뙆�씪 �떎�젣�씠由�    
    F_SIZE NUMBER NOT NULL, --�뙆�씪 �겕湲� KB
    F_URL VARCHAR2(4000) NOT NULL, --�뙆�씪 媛��긽�씠由�
    FOREIGN KEY(B_NO) REFERENCES DATA_BOARD(B_NO) ON DELETE CASCADE    
);

--紐⑥엫 寃뚯떆�뙋
CREATE TABLE MEET_BOARD(
    MEET_NO NUMBER PRIMARY KEY, --紐⑥엫 踰덊샇
    S_NO NUMBER NOT NULL,   --�뒪�꽣�뵒踰덊샇 [�쇅�옒�궎]
    MEET_TITLE VARCHAR2(1000) NOT NULL,--紐⑥엫 �젣紐�
    MEET_WRITER NUMBER NOT NULL, -- 紐⑥엫 �옉�꽦�옄 (�쉶�썝踰덊샇) [�쇅�옒�궎]
    MEET_CONTENT VARCHAR2(4000) NOT NULL, --紐⑥엫 �궡�슜,�꽕紐�
    MEET_ADDR VARCHAR2(1000) NOT NULL, --紐⑥엫 �룄濡쒕챸 二쇱냼
    MEET_ADDR_DETAIL VARCHAR2(500) NULL, --紐⑥엫 �긽�꽭二쇱냼
    MEET_DATE DATE NOT NULL, --紐⑥엫 �궇吏�
    MEET_TIME DATE NOT NULL, --紐⑥엫 �떆媛�
    MEET_REGDATE DATE NOT NULL,--紐⑥엫 �옉�꽦 �떆媛�
    VOTE_STARTDATE DATE NOT NULL, -- �닾�몴 �떆�옉�씪
    VOTE_ENDDATE DATE NOT NULL, --�닾�몴 留덇컧�씪
    MEET_CNT NUMBER DEFAULT 0, -- 議고쉶�닔
    FOREIGN KEY(S_NO) REFERENCES STUDY(S_NO) ON DELETE CASCADE,
    FOREIGN KEY(MEET_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE    
);
select * from meet_board;

--紐⑥엫 �닾�몴 
CREATE TABLE MEET_VOTE(
    MEET_NO NUMBER, --紐⑥엫踰덊샇
    MEM_NO NUMBER, --�쉶�썝踰덊샇
    VOTE_ATTEND VARCHAR2(1) DEFAULT 'D' CHECK (VOTE_ATTEND IN ('D','Y','N')) NOT NULL, --李몄꽍 �뿬遺�  誘명닾�몴,李몄꽍,遺덉갭
    PRIMARY KEY( MEET_NO, MEM_NO),
    FOREIGN KEY(MEET_NO) REFERENCES MEET_BOARD(MEET_NO) ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON DELETE CASCADE
);

--紐⑥엫 �뙎湲�
CREATE TABLE MEET_REPLY(
    R_NO NUMBER PRIMARY KEY, -- �뙎湲� 踰덊샇
    B_NO NUMBER NOT NULL, --寃뚯떆湲� 踰덊샇 (MEET_NO) DTO�넻�씪�븣臾몄뿉 B_NO濡쒖옟�쓬   
    R_GROUPNO NUMBER NOT NULL, -- �뙎湲� 洹몃９ 踰덊샇
    R_CLASS NUMBER NOT NULL, -- �뙎湲� 怨꾩링
    R_ORDER NUMBER NOT NULL,--�뙎湲�,�떟湲� �닚�꽌    
    R_WRITER NUMBER NOT NULL, -- �뙎湲� �옉�꽦�옄 (�쉶�썝踰덊샇)
    R_COMMENT VARCHAR2(1000) NOT NULL, --�뙎湲� �궡�슜
    R_REGDATE DATE NOT NULL,--�뙎湲� �옉�꽦 �떆媛�
    FOREIGN KEY(R_WRITER) REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE ,
    FOREIGN KEY(B_NO) REFERENCES MEET_BOARD(MEET_NO) ON DELETE CASCADE    
);


INSERT INTO STUDY_CATEGORY VALUES(1, 'IT');
INSERT INTO STUDY_CATEGORY VALUES(2, '�옄寃⑹쬆');
INSERT INTO STUDY_CATEGORY VALUES(3, '怨듬Т�썝');
INSERT INTO STUDY_CATEGORY VALUES(4, '酉고떚');
INSERT INTO STUDY_CATEGORY VALUES(5, '���엯/�닔�뒫');
INSERT INTO STUDY_CATEGORY VALUES(6, '�뼱�븰/�쉶�솕');
INSERT INTO STUDY_CATEGORY VALUES(7, '痍⑥뾽�뒪�꽣�뵒');
INSERT INTO STUDY_CATEGORY VALUES(8, '湲고�');

SELECT * FROM STUDY;

--�뒪�꽣�뵒 �떊泥� �듃由ш굅 
CREATE OR REPLACE TRIGGER study_trigger
AFTER INSERT ON STUDY
FOR EACH ROW
BEGIN 
if INSERTING then 
insert into study_member 
values(:NEW.S_NO,:NEW.LEADER_NO);

end if;
end;
/

--�뒪�꽣�뵒 媛��엯 �듃由ш굅
CREATE OR REPLACE TRIGGER JOIN_STUDY
AFTER UPDATE OF AGREE ON STUDY_APPLYING
FOR EACH ROW 
BEGIN 
    IF :NEW.AGREE = 'Y' THEN
    INSERT INTO STUDY_MEMBER VALUES(:OLD.S_NO,:OLD.MEM_NO);
    END IF;
    END;
/


COMMIT;
